on:
  push:

env:
  workdir: "demo"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout "
        uses: actions/checkout@v2

      - name: "Hashfile"
        env:
          OG: ${{ env.workdir }}
          RESULT: ${{ hashFiles(format('{0}/hashme.txt', env.workdir)) }}
        run:
          echo "Did it work? $RESULT"
